version: '3.4'

services:
  sql.data:
    image: microsoft/mssql-server-linux:2017-latest

  identity.simplified.api:
    image: identity.simplified.api:${TAG:-latest}
    build:
      context: .
      dockerfile: Identity.API/Dockerfile
    depends_on:
      - sql.data